# Generated by Django 4.0.4 on 2022-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.TextField(blank=True, verbose_name='Ссылка на картинку'),
        ),
    ]
