# Generated by Django 4.0.4 on 2022-04-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_dish_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='website.product', verbose_name='Ингредиенты'),
        ),
    ]
