# Generated by Django 4.0.4 on 2022-04-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_allergy_excluded_products_remove_dish_allergy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='allergies',
            new_name='allergy',
        ),
    ]
