# Generated by Django 4.0.4 on 2022-04-30 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_rename_allergies_category_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Чек пользователя'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='allergy',
            field=models.ManyToManyField(related_name='subscribes', to='website.allergy', verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to='website.preference', verbose_name='Предпочтения'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='shown_dishes',
            field=models.ManyToManyField(related_name='used_subscribes', to='website.dish', verbose_name='Показанные блюда'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
