# Generated by Django 4.0.4 on 2022-05-02 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_bill_user_alter_subscribe_allergy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='allergy',
            field=models.ManyToManyField(blank=True, related_name='subscribes', to='website.allergy', verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to='website.preference', verbose_name='Предпочтения'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='shown_dishes',
            field=models.ManyToManyField(blank=True, null=True, related_name='used_subscribes', to='website.dish', verbose_name='Показанные блюда'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscription_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Подписка была приобретена'),
        ),
    ]
