# Generated by Django 4.0.4 on 2022-05-02 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_subscribe_allergy_alter_subscribe_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='shown_dishes',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='subscription_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Подписка была приобретена'),
        ),
    ]
